const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  CLIENT_ADMIN: 'CLIENT_ADMIN',
  HR_OFFICER: 'HR_OFFICER',
  FINANCE_OFFICER: 'FINANCE_OFFICER',
  REPORTING_MANAGER: 'REPORTING_MANAGER',
  REGIONAL_MANAGER: 'REGIONAL_MANAGER',
  EMPLOYEE: 'EMPLOYEE',
};

const ALL_ROLES = Object.values(ROLES);

const CLIENT_PORTAL_ROLES = [
  ROLES.CLIENT_ADMIN,
  ROLES.HR_OFFICER,
  ROLES.FINANCE_OFFICER,
  ROLES.REPORTING_MANAGER,
  ROLES.REGIONAL_MANAGER,
];

module.exports = {
  ROLES,
  ALL_ROLES,
  CLIENT_PORTAL_ROLES,
};
