const LOAN_INTEREST_FORMULAS = {
  SIMPLE_INTEREST: 'SIMPLE_INTEREST',
  COMPOUND_INTEREST: 'COMPOUND_INTEREST',
};

const LOAN_INTEREST_FORMULA_LABELS = {
  [LOAN_INTEREST_FORMULAS.SIMPLE_INTEREST]: 'Simple Interest',
  [LOAN_INTEREST_FORMULAS.COMPOUND_INTEREST]: 'Compound Interest',
};

module.exports = {
  LOAN_INTEREST_FORMULAS,
  LOAN_INTEREST_FORMULA_LABELS,
  LOAN_INTEREST_FORMULA_VALUES: Object.values(LOAN_INTEREST_FORMULAS),
};
