export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  CLIENT_ADMIN: 'CLIENT_ADMIN',
  HR_OFFICER: 'HR_OFFICER',
  FINANCE_OFFICER: 'FINANCE_OFFICER',
  REPORTING_MANAGER: 'REPORTING_MANAGER',
  REGIONAL_MANAGER: 'REGIONAL_MANAGER',
  EMPLOYEE: 'EMPLOYEE',
};

export const ALL_ROLES = Object.values(ROLES);

export const ADMIN_PORTAL_ROLES = [ROLES.SUPER_ADMIN];